# arm-linux-gnueabihf-ar
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabihf-ar.1.gz
complete -c arm-linux-gnueabihf-ar -l help --description 'Displays the list of command line options supported by ar and then exits.'
complete -c arm-linux-gnueabihf-ar -l version --description 'Displays the version information of ar and then exits.'

