# debconf-mergetemplate
# Autogenerated from man page /usr/share/man/man1/debconf-mergetemplate.1.gz
complete -c debconf-mergetemplate -l outdated --description 'Merge in even outdated translations.'

