# hardlink
# Autogenerated from man page /usr/share/man/man1/hardlink.1.gz
complete -c hardlink -s h -l help --description 'print quick usage details to the screen.'
complete -c hardlink -s v -l verbose --description 'More verbose output.'
complete -c hardlink -s n -l dry-run --description 'Do not act, just print what would happen.'
complete -c hardlink -s f -l respect-name --description 'Only try to link files with the same (basename).'
complete -c hardlink -s p -l ignore-mode --description 'Link/compare files even if their mode is different.'
complete -c hardlink -s o -l ignore-owner --description 'Link/compare files even if their owner (user and group) is different.'
complete -c hardlink -s t -l ignore-time --description 'Link/compare files even if their time of modification is different.'
complete -c hardlink -s X -l respect-xattrs --description 'Only try to link files with the same extended attributes.'
complete -c hardlink -s m -l maximize --description 'Among equal files, keep the file with the highest link count.'
complete -c hardlink -s M -l minimize --description 'Among equal files, keep the file with the lowest link count.'
complete -c hardlink -s O -l keep-oldest --description 'Among equal files, keep the oldest file (least recent modification time).'
complete -c hardlink -s x -l exclude --description 'A regular expression which excludes files from being compared and linked.'
complete -c hardlink -s i -l include --description 'A regular expression to include files.'
complete -c hardlink -s s -l minimum-size --description 'The minimum size to consider.'

