# modeline2fb
# Autogenerated from man page /usr/share/man/man1/modeline2fb.1.gz
complete -c modeline2fb -s d -l depth --description 'Use the given display depth (default is 8).'
complete -c modeline2fb -s h -l help --description 'Print out a help screen and exit.  ADVANCED OPTIONS.'
complete -c modeline2fb -s r -l rounding --description 'Sets the vxres divisor (default is 128).'
complete -c modeline2fb -s x -l vxres --description 'Sets extra vxres values.'

