# ncdu
# Autogenerated from man page /usr/share/man/man1/ncdu.1.gz
complete -c ncdu -s h --description 'Print a short help message and quit.'
complete -c ncdu -s v --description 'Print ncdu version and quit.'
complete -c ncdu -s f --description 'Load the given file, which has earlier been created with the \\f(CW\\*(C`-o\\*(C…'
complete -c ncdu -s o --description 'Export all necessary information to \\s-1FILE\\s0 instead of opening the browse…'
complete -c ncdu -s 0 --description 'Don\'t give any feedback while scanning a directory or importing a file, other…'
complete -c ncdu -s 1 --description 'Similar to \\f(CW\\*(C`-0\\*(C\', but does give feedback on the scanning progress…'
complete -c ncdu -s 2 --description 'Provide a full-screen ncurses interface while scanning a directory or importi…'
complete -c ncdu -s q --description 'Quiet mode.'
complete -c ncdu -s r --description 'Read-only mode.  This will disable the built-in file deletion feature.'
complete -c ncdu -l si --description 'List sizes using base 10 prefixes, that is, powers of 1000 (\\s-1KB, MB,\\s0 et…'
complete -c ncdu -l confirm-quit --description 'Requires a confirmation before quitting ncdu.'
complete -c ncdu -s x --description 'Do not cross filesystem boundaries, i. e.'
complete -c ncdu -l exclude --description 'Exclude files that match \\s-1PATTERN\\s0.'
complete -c ncdu -s X -l exclude-from --description 'Exclude files that match any pattern in \\s-1FILE\\s0.'

