# paxctld
# Autogenerated from man page /usr/share/man/man8/paxctld.8.gz
complete -c paxctld -s c --description 'Specify a config file other than the default of \\%/etc/paxctld. conf.'
complete -c paxctld -s d --description 'Make paxctld run as a daemon.'
complete -c paxctld -s p --description 'Specify the pid file to use when running in daemon mode.'
complete -c paxctld -s q --description 'Enable quiet mode to suppress all syslogs from paxctld.'

