# th-cmd
# Autogenerated from man page /usr/share/man/man1/th-cmd.1.gz
complete -c th-cmd -l socket --description 'The socket file opened by the running triggerhappy daemon instance.'
complete -c th-cmd -l add --description 'Instruct the running daemon to open the input devices specified on the comman…'
complete -c th-cmd -l remove --description 'Remove specified devices from the running daemon.'
complete -c th-cmd -l clear --description 'Remove all devices from the running daemon.'
complete -c th-cmd -l udev --description 'Deduce operation and device name from udev environment (for use in udev rules…'
complete -c th-cmd -l disable --description 'Disable the execution of triggers.'
complete -c th-cmd -l enable --description 'Re-enable the execution of triggers.'
complete -c th-cmd -l mode --description 'Change the mode of the triggerhappy daemon to <newmode>.'
complete -c th-cmd -l quit --description 'Terminate the triggerhappy daemon.'
complete -c th-cmd -l passfd --description 'Instead of instructing the daemon to open the device, open the device and pas…'
complete -c th-cmd -l grab --description 'Grab the device; the triggerhappy daemon will try to get exclusive access to …'

