# thd
# Autogenerated from man page /usr/share/man/man1/thd.1.gz
complete -c thd -l help --description 'Shows usage instructions.'
complete -c thd -l listevents --description 'Prints a list of all known event names.'
complete -c thd -l triggers --description 'Read trigger definitions from conf, which can either be a file or a directory.'
complete -c thd -l dump --description 'Dump all recognized events to \\s-1STDOUT.'
complete -c thd -l socket --description 'Open a unix domain socket at file; this socket can be used to send commands t…'
complete -c thd -l daemon --description 'Run as a background daemon and detach from the terminal.'
complete -c thd -l pidfile --description 'Write \\s-1PID\\s0 to file.'
complete -c thd -l uinput --description 'Open uinput file (probably /dev/input/uinput) to generate synthetic events.'
complete -c thd -l ignore --description 'Ignore key and switch event labeled eventname.'
complete -c thd -l normalize --description 'Normalize \\s-1REL\\s0 and \\s-1ABS\\s0 events.'
complete -c thd -l user --description 'Change to user id name after opening files.'

